version: '3.7'

services:
  app:
    build: ./app
    command: opentelemetry-instrument gunicorn app:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:80 --reload
    ports:
      - "8000:80"
    environment:
      - OTEL_TRACES_EXPORTER=jaeger_thrift
      - OTEL_SERVICE_NAME=app
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces

  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"