version: "3.7"

services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    environment:
      - JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+ExitOnOutOfMemoryError
    restart: always
    ports:
      - "9411:9411"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.88.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP Http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  app_1:
    build:
      context: ./app_2
      dockerfile: Dockerfile
    command: opentelemetry-instrument uvicorn app:app --port $APP_1_PORT --host 0.0.0.0
    volumes:
      - ./app_1:/app # Mount the code directory into the container
    ports:
      - "${APP_1_PORT}:${APP_1_PORT}"
    environment:
      - OTEL_SERVICE_NAME=app_1
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
      - APP_1_PORT=$APP_1_PORT
      - APP_2_PORT=$APP_2_PORT
#      - GRPC_VERBOSITY=debug # Uncomment for debug, if you face "Transient error StatusCode..."
#      - GRPC_TRACE=http,call_error,connectivity_state # Uncomment for debug, if you face "Transient error StatusCode..."
  app_2:
    build:
      context: ./app_2
      dockerfile: Dockerfile
    command: opentelemetry-instrument uvicorn app:app --port $APP_2_PORT --host 0.0.0.0
    volumes:
      - ./app_2:/app # Mount the code directory into the container
    ports:
      - "${APP_2_PORT}:${APP_2_PORT}"
    environment:
      - OTEL_SERVICE_NAME=app_2
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4317
      - APP_1_PORT=$APP_1_PORT
      - APP_2_PORT=$APP_2_PORT
#      - GRPC_VERBOSITY=debug # Uncomment for debug, if you face "Transient error StatusCode..."
#      - GRPC_TRACE=http,call_error,connectivity_state # Uncomment for debug, if you face "Transient error StatusCode..."